In [1]:
# Transpose = flipping rows and columns
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("A shape:", A.shape)
print("A.T shape:", A.T.shape)

print(A.T)

A shape: (2, 3)
A.T shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [2]:
# Inverse = finding a matrix that when multiplied with the original matrix gives the identity matrix
A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalg.inv(A)

print("Inverse of A:")
print(A_inv)
print("A x A-1  =")
print(( A @ A_inv).round(0)) 

Inverse of A:
[[ 0.6 -0.7]
 [-0.2  0.4]]
A x A-1  =
[[ 1.  0.]
 [-0.  1.]]
